package dat.enums;

public enum ProfanityWords {// Danske bandeord
    LORT, PIS, RØV, PIK, FISSE, KÆLLING, LUDER, SKOD, KRAFTEDEME, FORBANDET,
            FOR_SATAN, FOR_FANDEN, HELVEDE, SGU, SATANS, MØG, SKIDE, SKIDERIK,
            IDIOT, FJOLS, ÅNDSSVAG, KLAPHAT, SPASSER, DRANKER, DRUKMÅS, DRUKNAR,
            DRUKNET, DRUK, DRUKRØV, DRUKABE, DRUKSVIN, DRUKFÅR, DRUKHOVED, DRUKMULE,
            DRUKNÆSE, DRUKØRE, DRUKSKALLE, DRUKØGLE,TABER, KÆMPE_NOOB, LORTESPIL, PIS_NOOB, WALLHACKER,
        AIM_BOTTER, DUM_BOT, LORTE_TEAMMATE, SOLO_QUEUE_CANCER,
        MEGA_FEEDER, TOTALT_BOOSTED,

            // Engelske bandeord
            FUCK, SHIT, BITCH, ASSHOLE, BASTARD, DAMN, CRAP, DICK, PISS, CUNT,
            MOTHERFUCKER, PRICK, TWAT, WANKER, BOLLOCKS, BUGGER, ARSEHOLE, TOSSER,
            GIT, JERK, SLUT, WHORE, SKANK, HOE, NIGGER, FAGGOT, RETARD, MORON,
            DUMBASS, JACKASS, DIPSHIT, SHITHEAD, DOUCHEBAG, ASSHAT, FUCKWIT, SHITFACE,
            COCK, PUSSY, DOUCHE, SCUMBAG, DICKHEAD, TWIT, ARSE, CRIKEY, BLOODY,
            HELL, SOD, WANK, PILLOCK, MUPPET, NUMPTY, BERK, PLONKER, TWONK, PRAT,
            KNOB, BELLEND, SHITBAG, FUCKFACE, ARSEWIPE, SHITSTAIN, DICKWAD, FUCKTARD,
            COCKWOMBLE, TWATWAFFLE, COCKSUCKER, MOTHERFUCKING, SHITFACED, ASSWIPE,
            FUCKHEAD, SHITLORD, ASSCLOWN, FUCKNUT, DOUCHECANOE, TWATFACE, COCKHEAD,
            ASSMUNCH, FUCKBOY, NOOB, TRASH, GIT_GUD, GET_REKT, EZ, CLOWN, BOT, SCRUB, CAMPER, CHEATER,
        HACKER, SMURF, FEEDER, BOOSTED, INT, TROLL, GRIEF, RAGEQUIT, TOXIC, REPORT
}
